### PR TITLE
Allow date or dateTime in documentCreationDate

### LINKED ISSUE #1: ebuttm:documentCreationDate doesn't allow xs:dateTime
The element `ebuttm:documentCreationDate` [current only allows `xs:date`](https://github.com/ebu/ebu-tt-m-xsd/blob/master/ebu-tt-metadata.xsd#L353). However Part M in § 3.11 also allows `xs:dateTime` here.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Closes #1.

### CODE REVIEW

**Review by spoeschel — COMMENTED** [review]
While the actual fix addresses the issue, merging it alone will not completely fix the issue:

EBU-TT's `ebutt.xsd` as well as EBU-TT Part M's `ebu-tt-metadata-xsd` (whereby the latter is used by the former) both import ([1](https://github.com/ebu/ebu-tt-xsd/blob/master/ebutt.xsd#L22), [2](https://github.com/ebu/ebu-tt-m-xsd/blob/master/ebu-tt-metadata.xsd#L17)) separate XSDs (`ebutt_datatypes.xsd` and `ebu-tt-datatypes.xsd` respectively) for the `urn:ebu:tt:datatypes` namespace. Up to now, both files have been equal (besides the top comment and the order of the `fontSizeType` type). With this fix, this is changed.

It seems to be implementation-defined how multiple locations for the same namespace are to be handled (edit: see also the [end of § 4.2.3 here](https://www.w3.org/TR/xmlschema-1/#composition-schemaImport)). At least the validator I use (Saxon EE) uses EBU-TT's version and therefore fails to validate an example, as `ebuttdt:creationDateType` cannot be found.

So the question is, whether/how the two files that target the same namespace should be handled (rather to say: kept in sync) here...

**Comment by nigelmegitt** [comment]
Hmm that's an interesting one - the data types are not actually specified to be in any particular namespace in Tech3390, which looks like an error. Although the `ebuttdt` prefix is used, it isn't defined in the Namespaces section. That looks like another spec bug. 

Proposal: change the namespace and prefix used in this repo's `ebu-tt-datatypes.xsd` to be metadata-specific, with prefix `ebuttmdt` ->  URN `urn:ebu:tt:metadata-datatypes` and change the filename to `ebu-tt-metadata-datatypes.xsd`. Thoughts @spoeschel ?

**Comment by spoeschel** [comment]
Hmm, what would this mean to used types like `ebuttdt:smpteTimingType`? I would prefer do not redefine them with exactly the same definition but just a different namespace URI. For the datatypes used only in the XSD (and not in the spec, e.g. the affected `ebuttdt:creationDateType`), renaming would be fine though.

**Comment by nigelmegitt** [comment]
You're saying leave it as `ebuttdt` prefix, and duplicate the definition, but point the prefix at a different URN?

**Comment by spoeschel** [comment]
For types that are already present in Part 1 (like `ebuttdt:smpteTimingType`) I wonder whether it would make sense (and be possible) to still refer to the Part 1 namespace here (and keep the `ebuttdt` prefix, too). As redefining a type in Part M instead would be redundancy somehow.

So in the end there would be two namespaces used for type definitions: Reusing particular types from Part 1, where possible/meaningful, as well as defining new types that are only used by Part M.

What do you think?

**Comment by nigelmegitt** [comment]
That would create a circular dependency in the repo, where the ebu-tt-m-xsd needs to include the part 1 xsd, and the part 1 xsd needs to include ebu-tt-m-xsd.

I'm reluctant to specify yet another xsd just for the datatypes.

Here's another proposal: 

Why don't we just leave pull request as it is, since there's nothing actually wrong with it? Instead, open a related issue on the ebu-tt-xsd repo pointing out that it does not need to redefine data types defined for metadata, and can simply use them, or if it is going to redefine them, then the definition needs to be updated to fix the same issue.

**Comment by spoeschel** [comment]
Hmm, indeed circular dependency :-/

OK, I will open a new issue at the EBU-TT repo to continue the discussion there.

**Review by spoeschel — APPROVED** [review]

**Comment by spoeschel** [comment]
I opened https://github.com/ebu/ebu-tt-xsd/issues/17 and https://github.com/ebu/ebu-tt-m-xsd/issues/25.

**Pull request merged**
